services:
  - type: web
    name: ontrack-zh
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    staticFiles:
      - source: app/static
        destination: /static
